spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: true